### ISSUE TITLE
Great stuff  - still maintained?

### ISSUE THREAD

**Issue by binarykitchen** [Aerilym/winston-axios#10]
I've searched in many places for custom error transports to your own server via Winston and that was the best found so far.

Surprised there isn't anything else out there, or am I missing something?

But then, this hasn't been maintained for 2 years ....

**Comment by Aerilym** [comment]
Glad you've had success with it! I've not really seen any need in making changes, but i do see there are some potential minor security concerns so I'll see that they get fixed. If there's anything you'd like to see changed feel free to contribute or create an issue for me (or others) to look into.

**Comment by Aerilym** [comment]
I've cleaned some stuff up, if you have any feature requests please create new issues for them.
